/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiStreamingChannelResponse struct {
	ClanId string `json:"clanId,omitempty"`
	ChannelId string `json:"channelId,omitempty"`
	StreamingUrl string `json:"streamingUrl,omitempty"`
	IsStreaming bool `json:"isStreaming,omitempty"`
}
