/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiClanWebhook struct {
	// id.
	Id string `json:"id,omitempty"`
	// webhook name.
	WebhookName string `json:"webhookName,omitempty"`
	// clan id.
	ClanId string `json:"clanId,omitempty"`
	// active.
	Active int32 `json:"active,omitempty"`
	// URL of the webhook, which is automatically generated and different from the avatar.
	Url string `json:"url,omitempty"`
	// creator id.
	CreatorId string `json:"creatorId,omitempty"`
	Avatar string `json:"avatar,omitempty"`
	// create time.
	CreateTime string `json:"createTime,omitempty"`
	// update time.
	UpdateTime string `json:"updateTime,omitempty"`
}
