/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ApiWalletLedger struct {
	Id string `json:"id,omitempty"`
	UserId string `json:"userId,omitempty"`
	CreateTime time.Time `json:"createTime,omitempty"`
	Value int32 `json:"value,omitempty"`
	TransactionId string `json:"transactionId,omitempty"`
}
