/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiRegistrationEmailRequest struct {
	// A valid RFC-5322 email address.
	Email string `json:"email,omitempty"`
	// A password for the user account.
	Password string `json:"password,omitempty"`
	// Set the username on the account at register. Must be unique.
	Username string `json:"username,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	AvatarUrl string `json:"avatarUrl,omitempty"`
	Dob string `json:"dob,omitempty"`
	// Extra information that will be bundled in the session token.
	Vars map[string]string `json:"vars,omitempty"`
}
