/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// A message sent on a channel.
type ApiChannelMessage struct {
	// The clan this message belong to.
	ClanId string `json:"clanId,omitempty"`
	// The channel this message belongs to.
	ChannelId string `json:"channelId,omitempty"`
	// The unique ID of this message.
	MessageId string `json:"messageId,omitempty"`
	// The code representing a message type or category.
	Code int32 `json:"code,omitempty"`
	// Message sender, usually a user ID.
	SenderId string `json:"senderId,omitempty"`
	// The username of the message sender, if any.
	Username string `json:"username,omitempty"`
	Avatar string `json:"avatar,omitempty"`
	// The content payload.
	Content string `json:"content,omitempty"`
	// The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was created.
	CreateTime time.Time `json:"createTime,omitempty"`
	// The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was last updated.
	UpdateTime time.Time `json:"updateTime,omitempty"`
	// The name of the chat room, or an empty string if this message was not sent through a chat room.
	ChannelLabel string `json:"channelLabel,omitempty"`
	ClanLogo string `json:"clanLogo,omitempty"`
	CategoryName string `json:"categoryName,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	ClanNick string `json:"clanNick,omitempty"`
	ClanAvatar string `json:"clanAvatar,omitempty"`
	Reactions string `json:"reactions,omitempty"`
	Mentions string `json:"mentions,omitempty"`
	Attachments string `json:"attachments,omitempty"`
	References string `json:"references,omitempty"`
	ReferencedMessage string `json:"referencedMessage,omitempty"`
	CreateTimeSeconds int64 `json:"createTimeSeconds,omitempty"`
	UpdateTimeSeconds int64 `json:"updateTimeSeconds,omitempty"`
	Mode int32 `json:"mode,omitempty"`
	HideEditted bool `json:"hideEditted,omitempty"`
	IsPublic bool `json:"isPublic,omitempty"`
}
