/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiChannelDescription struct {
	ClanId string `json:"clanId,omitempty"`
	// The parrent channel this message belongs to.
	ParrentId string `json:"parrentId,omitempty"`
	// The channel this message belongs to.
	ChannelId string `json:"channelId,omitempty"`
	CategoryId string `json:"categoryId,omitempty"`
	CategoryName string `json:"categoryName,omitempty"`
	// The channel type.
	Type_ int32 `json:"type,omitempty"`
	// creator ID.
	CreatorId string `json:"creatorId,omitempty"`
	ChannelLabel string `json:"channelLabel,omitempty"`
	ChannelPrivate int32 `json:"channelPrivate,omitempty"`
	ChannelAvatar []string `json:"channelAvatar,omitempty"`
	UserId []string `json:"userId,omitempty"`
	LastSentMessage *ApiChannelMessageHeader `json:"lastSentMessage,omitempty"`
	LastSeenMessage *ApiChannelMessageHeader `json:"lastSeenMessage,omitempty"`
	IsOnline []bool `json:"isOnline,omitempty"`
	MeetingCode string `json:"meetingCode,omitempty"`
	CountMessUnread int32 `json:"countMessUnread,omitempty"`
	Active int32 `json:"active,omitempty"`
	LastPinMessage string `json:"lastPinMessage,omitempty"`
	Usernames string `json:"usernames,omitempty"`
	CreatorName string `json:"creatorName,omitempty"`
	CreateTimeSeconds int64 `json:"createTimeSeconds,omitempty"`
	UpdateTimeSeconds int64 `json:"updateTimeSeconds,omitempty"`
	// Additional information stored as a JSON object.
	Metadata []string `json:"metadata,omitempty"`
	AboutMe []string `json:"aboutMe,omitempty"`
	ClanName string `json:"clanName,omitempty"`
	AppUrl string `json:"appUrl,omitempty"`
	IsMute bool `json:"isMute,omitempty"`
	AgeRestricted int32 `json:"ageRestricted,omitempty"`
	Topic string `json:"topic,omitempty"`
	E2ee int32 `json:"e2ee,omitempty"`
}
