/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A list of users belonging to a channel, along with their role.
type ApiChannelUserList struct {
	// User-role pairs for a channel.
	ChannelUsers []ChannelUserListChannelUser `json:"channelUsers,omitempty"`
	// Cursor for the next page of results, if any.
	Cursor string `json:"cursor,omitempty"`
	ChannelId string `json:"channelId,omitempty"`
}
