/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiLoginIdResponse struct {
	LoginId string `json:"loginId,omitempty"`
	Status int32 `json:"status,omitempty"`
	CreateTimeSecond string `json:"createTimeSecond,omitempty"`
	Platform string `json:"platform,omitempty"`
	UserId string `json:"userId,omitempty"`
	UserName string `json:"userName,omitempty"`
	Address string `json:"address,omitempty"`
}
