/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiRoleListEventResponse struct {
	Limit string `json:"limit,omitempty"`
	State string `json:"state,omitempty"`
	Cursor string `json:"cursor,omitempty"`
	ClanId string `json:"clanId,omitempty"`
	Roles *ApiRoleList `json:"roles,omitempty"`
}
