/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiWebhookGenerateResponse struct {
	Url string `json:"url,omitempty"`
	HookName string `json:"hookName,omitempty"`
	ChannelId string `json:"channelId,omitempty"`
	Avatar string `json:"avatar,omitempty"`
}
