/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiEditChannelCanvasRequest struct {
	Id string `json:"id,omitempty"`
	ChannelId string `json:"channelId,omitempty"`
	ClanId string `json:"clanId,omitempty"`
	Title string `json:"title,omitempty"`
	Content string `json:"content,omitempty"`
	IsDefault bool `json:"isDefault,omitempty"`
}
