/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiNotificationChannelCategorySetting struct {
	Id string `json:"id,omitempty"`
	ChannelCategoryLabel string `json:"channelCategoryLabel,omitempty"`
	NotificationSettingType int32 `json:"notificationSettingType,omitempty"`
	ChannelCategoryTitle string `json:"channelCategoryTitle,omitempty"`
	Action int32 `json:"action,omitempty"`
}
