/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Create a channel within clan.
type ApiCreateChannelDescRequest struct {
	ClanId string `json:"clanId,omitempty"`
	// The parrent channel this message belongs to.
	ParrentId string `json:"parrentId,omitempty"`
	// The channel this message belongs to.
	ChannelId string `json:"channelId,omitempty"`
	CategoryId string `json:"categoryId,omitempty"`
	// The channel type.
	Type_ int32 `json:"type,omitempty"`
	ChannelLabel string `json:"channelLabel,omitempty"`
	ChannelPrivate int32 `json:"channelPrivate,omitempty"`
	// The users to add.
	UserIds []string `json:"userIds,omitempty"`
	AppUrl string `json:"appUrl,omitempty"`
}
