/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A single user-role pair.
type ClanUserListClanUser struct {
	// User.
	User *ApiUser `json:"user,omitempty"`
	// Their relationship to the role.
	RoleId []string `json:"roleId,omitempty"`
	// from the `nick_name` field in the `clan_desc_profile` table.
	ClanNick string `json:"clanNick,omitempty"`
	// from the `avatar_url` field in the `clan_desc_profile` table.
	ClanAvatar string `json:"clanAvatar,omitempty"`
	ClanId string `json:"clanId,omitempty"`
}
