/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiClanDesc struct {
	CreatorId  string `json:"creator_id,omitempty"`
	ClanName   string `json:"clan_name,omitempty"`
	Logo       string `json:"logo,omitempty"`
	Banner     string `json:"banner,omitempty"`
	ClanId     string `json:"clan_id,omitempty"`
	Status     int32  `json:"status,omitempty"`
	BadgeCount int32  `json:"badge_count,omitempty"`
	// Is onboarding.
	IsOnboarding bool `json:"is_onboarding,omitempty"`
}
