/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiChannelMessageHeader struct {
	Id string `json:"id,omitempty"`
	TimestampSeconds int64 `json:"timestampSeconds,omitempty"`
	SenderId string `json:"senderId,omitempty"`
	Content string `json:"content,omitempty"`
	Attachment string `json:"attachment,omitempty"`
	Referece string `json:"referece,omitempty"`
	Mention string `json:"mention,omitempty"`
	Reaction string `json:"reaction,omitempty"`
}
