/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A list of apps.
type ApiAppList struct {
	// A list of apps.
	Apps []ApiApp `json:"apps,omitempty"`
	// Approximate total number of apps.
	TotalCount int32 `json:"totalCount,omitempty"`
	// Next cursor.
	NextCursor string `json:"nextCursor,omitempty"`
}
