/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A collection of zero or more friends of the user.
type ApiFriendList struct {
	// The Friend objects.
	Friends []ApiFriend `json:"friends,omitempty"`
	// Cursor for the next page of results, if any.
	Cursor string `json:"cursor,omitempty"`
}
