/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiPermissionUpdate struct {
	PermissionId string `json:"permissionId,omitempty"`
	Slug string `json:"slug,omitempty"`
	Type_ int32 `json:"type,omitempty"`
}
