/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// System message details.
type ApiSystemMessage struct {
	Id string `json:"id,omitempty"`
	ClanId string `json:"clanId,omitempty"`
	ChannelId string `json:"channelId,omitempty"`
	WelcomeRandom string `json:"welcomeRandom,omitempty"`
	WelcomeSticker string `json:"welcomeSticker,omitempty"`
	BoostMessage string `json:"boostMessage,omitempty"`
	SetupTips string `json:"setupTips,omitempty"`
}
