/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiRegistFcmDeviceTokenResponse struct {
	Token string `json:"token,omitempty"`
	DeviceId string `json:"deviceId,omitempty"`
	Platform string `json:"platform,omitempty"`
}
