/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiCategoryDesc struct {
	CreatorId string `json:"creatorId,omitempty"`
	ClanId string `json:"clanId,omitempty"`
	CategoryName string `json:"categoryName,omitempty"`
	CategoryId string `json:"categoryId,omitempty"`
	CategoryOrder int32 `json:"categoryOrder,omitempty"`
}
