/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiGenerateClanWebhookResponse struct {
	// clan id.
	ClanId string `json:"clanId,omitempty"`
	// url.
	Url string `json:"url,omitempty"`
	// webhook name.
	WebhookName string `json:"webhookName,omitempty"`
	// avatar.
	Avatar string `json:"avatar,omitempty"`
}
