/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ApiSetNotificationRequest struct {
	ChannelCategoryId string `json:"channelCategoryId,omitempty"`
	NotificationType int32 `json:"notificationType,omitempty"`
	TimeMute time.Time `json:"timeMute,omitempty"`
	ClanId string `json:"clanId,omitempty"`
}
