/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Log out a session, invalidate a refresh token, or log out all sessions/refresh tokens for a user.
type ApiSessionLogoutRequest struct {
	// Session token to log out.
	Token string `json:"token,omitempty"`
	// Refresh token to invalidate.
	RefreshToken string `json:"refreshToken,omitempty"`
	DeviceId string `json:"deviceId,omitempty"`
	FcmToken string `json:"fcmToken,omitempty"`
}
