/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Execute an Lua function on the server.
type ApiRpc struct {
	// The identifier of the function.
	Id string `json:"id,omitempty"`
	// The payload of the function which must be a JSON object.
	Payload string `json:"payload,omitempty"`
	// The authentication key used when executed as a non-client HTTP request.
	HttpKey string `json:"httpKey,omitempty"`
}
