/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiRole struct {
	Id string `json:"id,omitempty"`
	Title string `json:"title,omitempty"`
	Color string `json:"color,omitempty"`
	RoleIcon string `json:"roleIcon,omitempty"`
	Slug string `json:"slug,omitempty"`
	Description string `json:"description,omitempty"`
	CreatorId string `json:"creatorId,omitempty"`
	ClanId string `json:"clanId,omitempty"`
	Active int32 `json:"active,omitempty"`
	DisplayOnline int32 `json:"displayOnline,omitempty"`
	AllowMention int32 `json:"allowMention,omitempty"`
	RoleUserList *ApiRoleUserList `json:"roleUserList,omitempty"`
	PermissionList *ApiPermissionList `json:"permissionList,omitempty"`
	RoleChannelActive int32 `json:"roleChannelActive,omitempty"`
	ChannelIds []string `json:"channelIds,omitempty"`
	MaxLevelPermission int32 `json:"maxLevelPermission,omitempty"`
}
