/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiNotifiReactMessage struct {
	Id string `json:"id,omitempty"`
	UserId string `json:"userId,omitempty"`
	ChannelId string `json:"channelId,omitempty"`
}
