/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MezonUpdateWebhookByIdBody struct {
	WebhookName string `json:"webhookName,omitempty"`
	ChannelIdUpdate string `json:"channelIdUpdate,omitempty"`
	Avatar string `json:"avatar,omitempty"`
	ChannelId string `json:"channelId,omitempty"`
	ClanId string `json:"clanId,omitempty"`
}
