/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ApiClanSticker struct {
	Id string `json:"id,omitempty"`
	Source string `json:"source,omitempty"`
	Shortname string `json:"shortname,omitempty"`
	Category string `json:"category,omitempty"`
	CreatorId string `json:"creatorId,omitempty"`
	CreateTime time.Time `json:"createTime,omitempty"`
	ClanId string `json:"clanId,omitempty"`
	Logo string `json:"logo,omitempty"`
	ClanName string `json:"clanName,omitempty"`
}
