/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiSetMuteNotificationRequest struct {
	Id string `json:"id,omitempty"`
	NotificationType int32 `json:"notificationType,omitempty"`
	Active int32 `json:"active,omitempty"`
}
