/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ApiPinMessage struct {
	Id string `json:"id,omitempty"`
	MessageId string `json:"messageId,omitempty"`
	ChannelId string `json:"channelId,omitempty"`
	SenderId string `json:"senderId,omitempty"`
	Content string `json:"content,omitempty"`
	Username string `json:"username,omitempty"`
	Avatar string `json:"avatar,omitempty"`
	// The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was created.
	CreateTime time.Time `json:"createTime,omitempty"`
	CreateTimeSeconds int64 `json:"createTimeSeconds,omitempty"`
}
