/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A list of permission description, usually a result of a list operation.
type ApiPermissionList struct {
	// A list of permission.
	Permissions []ApiPermission `json:"permissions,omitempty"`
	MaxLevelPermission int32 `json:"maxLevelPermission,omitempty"`
}
