/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ApiEventManagement struct {
	Id string `json:"id,omitempty"`
	Title string `json:"title,omitempty"`
	Logo string `json:"logo,omitempty"`
	Description string `json:"description,omitempty"`
	Active int32 `json:"active,omitempty"`
	StartEvent int32 `json:"startEvent,omitempty"`
	CreatorId string `json:"creatorId,omitempty"`
	ClanId string `json:"clanId,omitempty"`
	ChannelId string `json:"channelId,omitempty"`
	Address string `json:"address,omitempty"`
	StartTime time.Time `json:"startTime,omitempty"`
	EndTime time.Time `json:"endTime,omitempty"`
	UserIds []string `json:"userIds,omitempty"`
	CreateTime time.Time `json:"createTime,omitempty"`
	MaxPermission int32 `json:"maxPermission,omitempty"`
}
