/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A single user-role pair.
type RoleUserListRoleUser struct {
	// The id of the user's account.
	Id string `json:"id,omitempty"`
	// The username of the user's account.
	Username string `json:"username,omitempty"`
	// The display name of the user.
	DisplayName string `json:"displayName,omitempty"`
	// A URL for an avatar image.
	AvatarUrl string `json:"avatarUrl,omitempty"`
	// The language expected to be a tag which follows the BCP-47 spec.
	LangTag string `json:"langTag,omitempty"`
	// The location set by the user.
	Location string `json:"location,omitempty"`
	// The timezone set by the user.
	Online bool `json:"online,omitempty"`
}
