/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiSearchMessageResponse struct {
	// List of paged messages.
	Messages []ApiSearchMessageDocument `json:"messages,omitempty"`
	// The total number of messages.
	Total int32 `json:"total,omitempty"`
}
