/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// A user with additional account details. Always the current user.
type ApiAccount struct {
	// The user object.
	User *ApiUser `json:"user,omitempty"`
	// The user's wallet data.
	Wallet string `json:"wallet,omitempty"`
	// The email address of the user.
	Email string `json:"email,omitempty"`
	// The devices which belong to the user's account.
	Devices []ApiAccountDevice `json:"devices,omitempty"`
	// The custom id in the user's account.
	CustomId string `json:"customId,omitempty"`
	// The UNIX time (for gRPC clients) or ISO string (for REST clients) when the user's email was verified.
	VerifyTime time.Time `json:"verifyTime,omitempty"`
	// The UNIX time (for gRPC clients) or ISO string (for REST clients) when the user's account was disabled/banned.
	DisableTime time.Time `json:"disableTime,omitempty"`
	Logo string `json:"logo,omitempty"`
	SplashScreen string `json:"splashScreen,omitempty"`
}
