/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiClanDesc struct {
	CreatorId string `json:"creatorId,omitempty"`
	ClanName string `json:"clanName,omitempty"`
	Logo string `json:"logo,omitempty"`
	Banner string `json:"banner,omitempty"`
	ClanId string `json:"clanId,omitempty"`
	Status int32 `json:"status,omitempty"`
	BadgeCount int32 `json:"badgeCount,omitempty"`
	// Is onboarding.
	IsOnboarding bool `json:"isOnboarding,omitempty"`
}
