/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MezonUpdateCategoryBody struct {
	// The ID of the group to update.
	CategoryId string `json:"categoryId,omitempty"`
	CategoryName string `json:"categoryName,omitempty"`
}
