/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiClanDescProfile struct {
	ClanId string `json:"clanId,omitempty"`
	CreatorId string `json:"creatorId,omitempty"`
	NickName string `json:"nickName,omitempty"`
	ProfileBanner string `json:"profileBanner,omitempty"`
	ProfileTheme string `json:"profileTheme,omitempty"`
	AvatarUrl string `json:"avatarUrl,omitempty"`
}
