/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Update fields in a given role.
type MezonUpdateRoleBody struct {
	Title string `json:"title,omitempty"`
	Color string `json:"color,omitempty"`
	RoleIcon string `json:"roleIcon,omitempty"`
	Description string `json:"description,omitempty"`
	DisplayOnline int32 `json:"displayOnline,omitempty"`
	AllowMention int32 `json:"allowMention,omitempty"`
	// The users to add.
	AddUserIds []string `json:"addUserIds,omitempty"`
	// The permissions to add.
	ActivePermissionIds []string `json:"activePermissionIds,omitempty"`
	// The users to remove.
	RemoveUserIds []string `json:"removeUserIds,omitempty"`
	// The permissions to remove.
	RemovePermissionIds []string `json:"removePermissionIds,omitempty"`
	ClanId string `json:"clanId,omitempty"`
	MaxPermissionId string `json:"maxPermissionId,omitempty"`
}
