/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiOssrsHttpCallbackRequest struct {
	Action string `json:"action,omitempty"`
	ClientId string `json:"clientId,omitempty"`
	Ip string `json:"ip,omitempty"`
	Vhost string `json:"vhost,omitempty"`
	App string `json:"app,omitempty"`
	Stream string `json:"stream,omitempty"`
	Param string `json:"param,omitempty"`
	ServerId string `json:"serverId,omitempty"`
	StreamUrl string `json:"streamUrl,omitempty"`
	StreamId string `json:"streamId,omitempty"`
	PageUrl string `json:"pageUrl,omitempty"`
	TcUrl string `json:"tcUrl,omitempty"`
	ServiceId string `json:"serviceId,omitempty"`
}
