/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Add link invite users to.
type ApiLinkInviteUserRequest struct {
	// id clan to add link to .
	ClanId string `json:"clanId,omitempty"`
	// id channel to add link to.
	ChannelId string `json:"channelId,omitempty"`
	ExpiryTime int32 `json:"expiryTime,omitempty"`
}
