/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiSearchMessageDocument struct {
	// The message ID.
	MessageId string `json:"messageId,omitempty"`
	// The channel ID.
	ChannelId string `json:"channelId,omitempty"`
	// The clan ID.
	ClanId string `json:"clanId,omitempty"`
	// The user ID of sender.
	SenderId string `json:"senderId,omitempty"`
	Content string `json:"content,omitempty"`
	Mention string `json:"mention,omitempty"`
	Reaction string `json:"reaction,omitempty"`
	Attachments []ApiMessageAttachment `json:"attachments,omitempty"`
	Reference string `json:"reference,omitempty"`
	CreateTime string `json:"createTime,omitempty"`
	UpdateTime string `json:"updateTime,omitempty"`
	ChannelLabel string `json:"channelLabel,omitempty"`
	ChannelType int32 `json:"channelType,omitempty"`
	ClanName string `json:"clanName,omitempty"`
	Username string `json:"username,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	AvatarUrl string `json:"avatarUrl,omitempty"`
}
