/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Represents an event to be passed through the server to registered event handlers.
type MezonapiEvent struct {
	// An event name, type, category, or identifier.
	Name string `json:"name,omitempty"`
	// Arbitrary event property values.
	Properties map[string]string `json:"properties,omitempty"`
	// The time when the event was triggered.
	Timestamp time.Time `json:"timestamp,omitempty"`
	// True if the event came directly from a client call, false otherwise.
	External bool `json:"external,omitempty"`
}
