/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiRoleUserList struct {
	// role_users pairs for a clan.
	RoleUsers []RoleUserListRoleUser `json:"roleUsers,omitempty"`
	// Cursor for the next page of results, if any.
	Cursor string `json:"cursor,omitempty"`
}
