/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ApiNotificationUserChannel struct {
	Id string `json:"id,omitempty"`
	NotificationSettingType int32 `json:"notificationSettingType,omitempty"`
	TimeMute time.Time `json:"timeMute,omitempty"`
	Active int32 `json:"active,omitempty"`
}
