/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiChannelSettingItem struct {
	Id string `json:"id,omitempty"`
	CreatorId string `json:"creatorId,omitempty"`
	ParentId string `json:"parentId,omitempty"`
	ChannelLabel string `json:"channelLabel,omitempty"`
	CategoryId string `json:"categoryId,omitempty"`
	MeetingCode string `json:"meetingCode,omitempty"`
	ChannelPrivate int32 `json:"channelPrivate,omitempty"`
	ChannelType int32 `json:"channelType,omitempty"`
	Active int32 `json:"active,omitempty"`
	UserIds []string `json:"userIds,omitempty"`
	MessageCount string `json:"messageCount,omitempty"`
	LastSentMessage *ApiChannelMessageHeader `json:"lastSentMessage,omitempty"`
}
