/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Update fields in a given channel.
type MezonUpdateChannelDescBody struct {
	ChannelLabel string `json:"channelLabel,omitempty"`
	CategoryId string `json:"categoryId,omitempty"`
	AppUrl string `json:"appUrl,omitempty"`
	Topic string `json:"topic,omitempty"`
	AgeRestricted int32 `json:"ageRestricted,omitempty"`
	E2ee int32 `json:"e2ee,omitempty"`
}
