/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ApiAuditLog struct {
	Id string `json:"id,omitempty"`
	UserId string `json:"userId,omitempty"`
	ClanId string `json:"clanId,omitempty"`
	ActionLog string `json:"actionLog,omitempty"`
	EntityName string `json:"entityName,omitempty"`
	EntityId string `json:"entityId,omitempty"`
	Details string `json:"details,omitempty"`
	TimeLog time.Time `json:"timeLog,omitempty"`
}
