/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A user's session used to authenticate messages.
type ApiSession struct {
	// True if the corresponding account was just created, false otherwise.
	Created bool `json:"created,omitempty"`
	// Authentication credentials.
	Token string `json:"token,omitempty"`
	// Refresh token that can be used for session token renewal.
	RefreshToken string `json:"refreshToken,omitempty"`
	UserId string `json:"userId,omitempty"`
}
