/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A list of users belonging to a channel, along with their role.
type ApiStreamingChannelUser struct {
	Id string `json:"id,omitempty"`
	// user for a channel.
	UserId string `json:"userId,omitempty"`
	ChannelId string `json:"channelId,omitempty"`
	Participant string `json:"participant,omitempty"`
}
