/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MezonapiListAuditLog struct {
	TotalCount int32 `json:"totalCount,omitempty"`
	Page int32 `json:"page,omitempty"`
	PageSize int32 `json:"pageSize,omitempty"`
	Logs []ApiAuditLog `json:"logs,omitempty"`
}
