/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Add link invite users to.
type ApiInviteUserRes struct {
	// id clan to add link to .
	ClanId string `json:"clanId,omitempty"`
	// id channel to add link to.
	ChannelId string `json:"channelId,omitempty"`
	ClanName string `json:"clanName,omitempty"`
	ChannelLabel string `json:"channelLabel,omitempty"`
	UserJoined bool `json:"userJoined,omitempty"`
	ExpiryTime time.Time `json:"expiryTime,omitempty"`
}
