/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// A user in the server.
type ApiUser struct {
	// The id of the user's account.
	Id string `json:"id,omitempty"`
	// The username of the user's account.
	Username string `json:"username,omitempty"`
	// The display name of the user.
	DisplayName string `json:"displayName,omitempty"`
	// A URL for an avatar image.
	AvatarUrl string `json:"avatarUrl,omitempty"`
	// The language expected to be a tag which follows the BCP-47 spec.
	LangTag string `json:"langTag,omitempty"`
	// The location set by the user.
	Location string `json:"location,omitempty"`
	// The timezone set by the user.
	Timezone string `json:"timezone,omitempty"`
	// Additional information stored as a JSON object.
	Metadata string `json:"metadata,omitempty"`
	// The Facebook id in the user's account.
	FacebookId string `json:"facebookId,omitempty"`
	// The Google id in the user's account.
	GoogleId string `json:"googleId,omitempty"`
	// The Apple Game Center in of the user's account.
	GamecenterId string `json:"gamecenterId,omitempty"`
	// The Steam id in the user's account.
	SteamId string `json:"steamId,omitempty"`
	// Indicates whether the user is currently online.
	Online bool `json:"online,omitempty"`
	// Number of related edges to this user.
	EdgeCount int32 `json:"edgeCount,omitempty"`
	// The UNIX time (for gRPC clients) or ISO string (for REST clients) when the user was created.
	CreateTime time.Time `json:"createTime,omitempty"`
	// The UNIX time (for gRPC clients) or ISO string (for REST clients) when the user was last updated.
	UpdateTime time.Time `json:"updateTime,omitempty"`
	// The Apple Sign In ID in the user's account.
	AppleId string `json:"appleId,omitempty"`
	AboutMe string `json:"aboutMe,omitempty"`
	JoinTime time.Time `json:"joinTime,omitempty"`
	IsMobile bool `json:"isMobile,omitempty"`
	Dob time.Time `json:"dob,omitempty"`
}
