/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// A friend of a user.
type ApiFriend struct {
	// The user object.
	User *ApiUser `json:"user,omitempty"`
	// The friend status.  one of \"Friend.State\".
	State int32 `json:"state,omitempty"`
	// Time of the latest relationship update.
	UpdateTime time.Time `json:"updateTime,omitempty"`
}
