/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiHashtagDm struct {
	// The channel id.
	ChannelId string `json:"channelId,omitempty"`
	ChannelLabel string `json:"channelLabel,omitempty"`
	ClanId string `json:"clanId,omitempty"`
	ClanName string `json:"clanName,omitempty"`
	MeetingCode string `json:"meetingCode,omitempty"`
	Type_ int32 `json:"type,omitempty"`
	ChannelPrivate int32 `json:"channelPrivate,omitempty"`
	ParrentId string `json:"parrentId,omitempty"`
}
