/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiTokenSentEvent struct {
	SenderId string `json:"senderId,omitempty"`
	SenderName string `json:"senderName,omitempty"`
	ReceiverId string `json:"receiverId,omitempty"`
	Amount int32 `json:"amount,omitempty"`
	Note string `json:"note,omitempty"`
}
