/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiAllUsersAddChannelResponse struct {
	ChannelId string `json:"channelId,omitempty"`
	UserIds []string `json:"userIds,omitempty"`
	Limit int32 `json:"limit,omitempty"`
}
