/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Send an email with password to the server. Used with authenticate/link/unlink.
type ApiAccountEmail struct {
	// A valid RFC-5322 email address.
	Email string `json:"email,omitempty"`
	// A password for the user account.  Ignored with unlink operations.
	Password string `json:"password,omitempty"`
	// Extra information that will be bundled in the session token.
	Vars map[string]string `json:"vars,omitempty"`
}
