/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// App information.
type ApiApp struct {
	Id string `json:"id,omitempty"`
	Appname string `json:"appname,omitempty"`
	CreatorId string `json:"creatorId,omitempty"`
	Applogo string `json:"applogo,omitempty"`
	IsShadow bool `json:"isShadow,omitempty"`
	// The UNIX time when the app was disabled.
	DisableTime time.Time `json:"disableTime,omitempty"`
	Token string `json:"token,omitempty"`
	Role int32 `json:"role,omitempty"`
	About string `json:"about,omitempty"`
}
