/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiAddAppRequest struct {
	// The appname.
	Appname string `json:"appname,omitempty"`
	// The password.
	Token string `json:"token,omitempty"`
	// Creator of the app.
	CreatorId string `json:"creatorId,omitempty"`
	// Role of this app.
	Role int32 `json:"role,omitempty"`
	// Is shadow.
	IsShadow bool `json:"isShadow,omitempty"`
}
