/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// A notification in the server.
type ApiNotification struct {
	// ID of the Notification.
	Id string `json:"id,omitempty"`
	// Subject of the notification.
	Subject string `json:"subject,omitempty"`
	// Content of the notification in JSON.
	Content string `json:"content,omitempty"`
	// Category code for this notification.
	Code int32 `json:"code,omitempty"`
	// ID of the sender, if a user. Otherwise 'null'.
	SenderId string `json:"senderId,omitempty"`
	// The UNIX time (for gRPC clients) or ISO string (for REST clients) when the notification was created.
	CreateTime time.Time `json:"createTime,omitempty"`
	// True if this notification was persisted to the database.
	Persistent bool `json:"persistent,omitempty"`
	ClanId string `json:"clanId,omitempty"`
	ChannelId string `json:"channelId,omitempty"`
	ChannelType int32 `json:"channelType,omitempty"`
	AvatarUrl string `json:"avatarUrl,omitempty"`
}
