/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Link Steam to the current user's account.
type ApiLinkSteamRequest struct {
	// The Facebook account details.
	Account *ApiAccountSteam `json:"account,omitempty"`
	// Import Steam friends for the user.
	Sync bool `json:"sync,omitempty"`
}
