/*
 * Mezon API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Contact: hello@heroiclabs.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MezonUpdateClanStickerByIdBody struct {
	Source string `json:"source,omitempty"`
	Shortname string `json:"shortname,omitempty"`
	Category string `json:"category,omitempty"`
	ClanId string `json:"clanId,omitempty"`
}
